### PR TITLE
Add Client Class

### PR DESCRIPTION
**Pull request by Aishwarya-Hariharan-Iyer**
## DESIGN
Client class extending Person class with this design:
- Client name only mandatory field for constructing
 
## RATIONALE
Client class created to provide flexibility in creating Persons who are clients as:
- Not all client details are mandatory but all Person fields are mandatory
- Tags in Client class can be restricted to "manager", "private", etc.
- Existing tests for Person class supported and Client-specific tests can be added.

## BENEFITS
- Supports creating other Person sub-classes like "Teammate", "Lead", etc. later on.
- Supports creating types of clients later such as 'Office', 'NGO', etc.

### CODE REVIEW

**Comment by Yongbeom-Kim** [comment]
I'll continue the thread here: I'd ask you to help me refactor the package structure of the current project.

One of the good points on the packaging is that (1) it provides some sort of hierarchical structure in code, and (2) that package visibilities help out a pretty good amount in organising code. That is to say, best practice is to avoid imports _across_ packages, for imports within (sub)packages. From my experience, imports across packages are a sort of antipattern - they make messy, spaghetti code over time. Would recommend either moving Client.java into the `model.person` package, or creating a `model.person.client` package instead.

Regarding _people_, I am unsure whether the Person class is even needed at this stage. We are only keeping track of Clients, correct? I would recommend either deleting the Person class, or if you see any other subclasses of Person.java, I would recommend changing it to an abstract class at this moment.

**Comment by Yongbeom-Kim** [comment]
Other than that, as @ConradLew mentioned, I'm not too sure about keeping the `Tag` class, but I guess we can keep it right now, it isn't too important - I'll leave the decision up to you @Aishwarya-Hariharan-Iyer 

Other than that, LGTM!

**Comment by Aishwarya-Hariharan-Iyer** [comment]
> Other than that, as @ConradLew mentioned, I'm not too sure about keeping the `Tag` class, but I guess we can keep it right now, it isn't too important - I'll leave the decision up to you @Aishwarya-Hariharan-Iyer
> 
> Other than that, LGTM!

Tysm for the suggestions! Thanks @ConradLew too for all the suggestions including the ones in the [linked thread](https://github.com/AY2223S1-CS2103-F13-1/tp/pull/30). @Yongbeom-Kim we considered removing the Tag and Address bits for Client but hesitated considering LSP. But that is a very important point that we might have to discuss in our meeting!

**Review by ConradLew — APPROVED** [review]
LGTM

**Pull request merged**
